# Generated by Django 5.0 on 2024-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_plan',
            field=models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid'), ('Expired', 'Expired')], max_length=20),
        ),
    ]
